--- Q58: Cho biet ten giao vien tham gia de tai du tat ca cac chu de
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT C.MACD
			FROM CHUDE AS C
		)
		EXCEPT
		(
			SELECT DISTINCT D1.MACD
			FROM  DETAI AS D1, THAMGIADT AS T1
			WHERE T1.MAGV = G.MAGV AND D1.MADT = T1.MADT
		)
	)
--- NOT EXISTS 
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND NOT EXISTS 
	(
		SELECT *
		FROM CHUDE AS C
		WHERE NOT EXISTS 
		(
			SELECT *
			FROM  DETAI AS D1, THAMGIADT AS T1
			WHERE T1.MAGV = G.MAGV AND D1.MADT = T1.MADT AND D1.MACD = C.MACD
		)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND D.MACD IN 
	(
		SELECT DISTINCT C.MACD
		FROM CHUDE AS C
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT D.MACD) = 
	(
		SELECT COUNT(C.MACD)
		FROM CHUDE AS C
	)

--- Q59: Cho biet ten de tai nao ma duoc tat ca cac giao vien cua bo mon HTTT tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G
			WHERE G.MABM =  'HTTT'	
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G
		WHERE G.MABM =  'HTTT'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = 'HTTT'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)

--- Q60: Cho biet ten de tai co tat ca giang vien bo mon 'He thong thong tin' tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G, BOMON AS B
			WHERE G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G, BOMON AS B
		WHERE G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)

--- Q61: Cho biet giao vien nao da tham gia tat ca cac de tai co ma chu de la QLGD
--- EXCEPT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		(
			SELECT D.MADT
			FROM DETAI AS D
			WHERE D.MACD = 'QLGD'
		)
		EXCEPT
		(
			SELECT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T.MAGV = T1.MAGV
		)
	)
--- NOT EXISTS
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
		AND NOT EXISTS 
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T.MAGV = T1.MAGV AND T1.MADT = D.MADT
			)
	)
--- COUNT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND T.MADT IN
	(
		SELECT D.MADT
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(D.MADT)
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
	)

---Q62: Cho biet ten giao vien tham gia tat cac ca de tai ma giao vien Tran Tra Huong da tham gia
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T1.MAGV = TTH.MAGV
		)
		EXCEPT
		(
			SELECT T2.MADT
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM THAMGIADT AS T1
		WHERE T1.MAGV = TTH.MAGV
		AND NOT EXISTS
		(
			SELECT *
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV AND T2.MADT = T1.MADT
		)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
AND T.MADT IN 
	(
		SELECT T1.MADT
		FROM THAMGIADT AS T1
		WHERE T1.MAGV = TTH.MAGV
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(DISTINCT T.MADT)
		FROM THAMGIADT AS T1, GIAOVIEN AS TT1
		WHERE T1.MAGV = TT1.MAGV AND TT1.HOTEN = N'Trần Trà Hương'
	)

--- Q63: Cho biet ten de tai nao ma duoc tat ca cac giao vien cua bo mon Hoa huu co tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G LEFT JOIN BOMON AS B ON G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G LEFT JOIN BOMON AS B ON G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)
