--- Q58: Cho biet ten giao vien tham gia de tai du tat ca cac chu de
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT C.MACD
			FROM CHUDE AS C
		)
		EXCEPT
		(
			SELECT DISTINCT D1.MACD
			FROM  DETAI AS D1, THAMGIADT AS T1
			WHERE T1.MAGV = G.MAGV AND D1.MADT = T1.MADT
		)
	)
--- NOT EXISTS 
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND NOT EXISTS 
	(
		SELECT *
		FROM CHUDE AS C
		WHERE NOT EXISTS 
		(
			SELECT *
			FROM  DETAI AS D1, THAMGIADT AS T1
			WHERE T1.MAGV = G.MAGV AND D1.MADT = T1.MADT AND D1.MACD = C.MACD
		)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, DETAI AS D, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT
	AND D.MACD IN 
	(
		SELECT DISTINCT C.MACD
		FROM CHUDE AS C
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT D.MACD) = 
	(
		SELECT COUNT(C.MACD)
		FROM CHUDE AS C
	)

--- Q59: Cho biet ten de tai nao ma duoc tat ca cac giao vien cua bo mon HTTT tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G
			WHERE G.MABM =  'HTTT'	
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G
		WHERE G.MABM =  'HTTT'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = 'HTTT'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)

--- Q60: Cho biet ten de tai co tat ca giang vien bo mon 'He thong thong tin' tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G, BOMON AS B
			WHERE G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G, BOMON AS B
		WHERE G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.TENBM = N'HỆ THỐNG THÔNG TIN'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)

--- Q61: Cho biet giao vien nao da tham gia tat ca cac de tai co ma chu de la QLGD
--- EXCEPT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		(
			SELECT D.MADT
			FROM DETAI AS D
			WHERE D.MACD = 'QLGD'
		)
		EXCEPT
		(
			SELECT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T.MAGV = T1.MAGV
		)
	)
--- NOT EXISTS
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
		AND NOT EXISTS 
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T.MAGV = T1.MAGV AND T1.MADT = D.MADT
			)
	)
--- COUNT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND T.MADT IN
	(
		SELECT D.MADT
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(D.MADT)
		FROM DETAI AS D
		WHERE D.MACD = 'QLGD'
	)

---Q62: Cho biet ten giao vien tham gia tat cac ca de tai ma giao vien Tran Tra Huong da tham gia
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T1.MAGV = TTH.MAGV
		)
		EXCEPT
		(
			SELECT T2.MADT
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM THAMGIADT AS T1
		WHERE T1.MAGV = TTH.MAGV
		AND NOT EXISTS
		(
			SELECT *
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV AND T2.MADT = T1.MADT
		)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
AND T.MADT IN 
	(
		SELECT T1.MADT
		FROM THAMGIADT AS T1
		WHERE T1.MAGV = TTH.MAGV
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(DISTINCT T.MADT)
		FROM THAMGIADT AS T1, GIAOVIEN AS TT1
		WHERE T1.MAGV = TT1.MAGV AND TT1.HOTEN = N'Trần Trà Hương'
	)

--- Q63: Cho biet ten de tai nao ma duoc tat ca cac giao vien cua bo mon Hoa huu co tham gia
--- EXCEPT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G LEFT JOIN BOMON AS B ON G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G LEFT JOIN BOMON AS B ON G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.TENBM = N'HÓA HỮU CƠ'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1
		WHERE G1.MABM = 'HTTT'
	)

--- Q64: Cho biet ten giao vien nao ma tham gia tat ca cac cong viec cua de tai 006
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT C.SOTT
			FROM CONGVIEC AS C 
			WHERE C.MADT = '006'			
		)
		EXCEPT
		(
			SELECT DISTINCT T1.STT
			FROM THAMGIADT AS T1
			WHERE T1.MAGV = T.MAGV AND T1.MADT = '006'
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM CONGVIEC AS C 
		WHERE C.MADT = '006'	
			AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T1.MAGV = T.MAGV AND T1.MADT = C.MADT AND T1.STT = C.SOTT
			)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV AND T.MADT = '006'
	AND T.STT IN
	(
		SELECT C.SOTT
		FROM CONGVIEC AS C
		WHERE C.MADT = '006'
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.STT) = 
	(
		SELECT COUNT(C.SOTT)
		FROM CONGVIEC AS C
		WHERE C.MADT = '006'
	)

--- Q65: Cho biet giao vien nao da tham gia tat ca cac de tai cua chu de Ung dung cong nghe
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT D.MADT
			FROM DETAI AS D, CHUDE AS C
			WHERE D.MACD = C.MACD AND C.TENCD = N'Ứng dụng công nghệ'
		)
		EXCEPT
		(
			SELECT DISTINCT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T.MAGV = T1.MAGV
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Ứng dụng công nghệ'
		AND NOT EXISTS 
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T.MAGV = T1.MAGV AND T1.MADT = D.MADT
			)
	)
--- COUNT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND T.MADT IN
	(
		SELECT D.MADT
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Ứng dụng công nghệ'
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(D.MADT)
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Ứng dụng công nghệ'
	)

--- Q66: Cho biet ten giao vien nao da tham gia tat ca cac de tai do Tran Tra Huong lam chu nhiem
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT D1.MADT 
			FROM DETAI AS D1
			WHERE D1.GVCNDT = TTH.MAGV
		)
		EXCEPT
		(
			SELECT DISTINCT T2.MADT
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D1
		WHERE D1.GVCNDT = TTH.MAGV
		AND NOT EXISTS
		(
			SELECT *
			FROM THAMGIADT AS T2
			WHERE T2.MAGV = T.MAGV AND T2.MADT = D1.MADT
		)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, GIAOVIEN AS TTH
WHERE G.MAGV = T.MAGV AND TTH.HOTEN = N'Trần Trà Hương' AND G.MAGV != TTH.MAGV
AND T.MADT IN 
	(
		SELECT D1.MADT 
		FROM DETAI AS D1
		WHERE D1.GVCNDT = TTH.MAGV
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(DISTINCT D2.MADT)
		FROM DETAI AS D2, GIAOVIEN AS TT1
		WHERE D2.GVCNDT = TT1.MAGV AND TT1.HOTEN = N'Trần Trà Hương'
	)

--- Q67: Cho biet ten de tai nao duoc tat ca cac giao vien cua khoa CNTT tham gia
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G, BOMON AS B
			WHERE G.MABM = B.MABM AND B.MAKHOA = 'CNTT'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G, BOMON AS B
		WHERE G.MABM = B.MABM AND B.MAKHOA = 'CNTT'	
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.MAKHOA = 'CNTT'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1, BOMON AS B1
		WHERE G1.MABM = B1.MABM AND B1.MAKHOA = 'CNTT'
	)

--- Q68: Cho biet ten giao vien nao ma tham gia tat ca cac cong viec cua de tai Nghien cuu te bao goc
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT C.SOTT
			FROM CONGVIEC AS C, DETAI AS D1
			WHERE C.MADT = D1.MADT AND D1.TENDT = N'Nghiên cứu tế bào gốc'			
		)
		EXCEPT
		(
			SELECT DISTINCT T1.STT
			FROM THAMGIADT AS T1, DETAI AS D2
			WHERE T1.MAGV = T.MAGV AND T1.MADT = D2.MADT AND D2.TENDT = N'Nghiên cứu tế bào gốc'	
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM CONGVIEC AS C, DETAI AS D1
		WHERE C.MADT = D1.MADT AND D1.TENDT = N'Nghiên cứu tế bào gốc'			
			AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T1.MAGV = T.MAGV AND T1.MADT = C.MADT AND T1.STT = C.SOTT
			)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, DETAI AS D
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT AND D.TENDT = N'Nghiên cứu tế bào gốc'	
	AND T.STT IN
	(
		SELECT DISTINCT C.SOTT
		FROM CONGVIEC AS C, DETAI AS D1
		WHERE C.MADT = D1.MADT AND D1.TENDT = N'Nghiên cứu tế bào gốc'		
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.STT) = 
	(
		SELECT COUNT(C.SOTT)
		FROM CONGVIEC AS C, DETAI AS D1
		WHERE C.MADT = D1.MADT AND D1.TENDT = N'Nghiên cứu tế bào gốc'		
	)

--- Q69: Tim ten cac giao vien duoc phan cong lam tat ca cac de tai co kinh phi tren 100 trieu
--- EXCEPT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		(
			SELECT D.MADT
			FROM DETAI AS D
			WHERE D.KINHPHI > 100
		)
		EXCEPT
		(
			SELECT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T.MAGV = T1.MAGV
		)
	)
--- NOT EXISTS
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D
		WHERE D.KINHPHI > 100
		AND NOT EXISTS 
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T.MAGV = T1.MAGV AND T1.MADT = D.MADT
			)
	)
--- COUNT
SELECT G.MAGV, G.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV 
	AND T.MADT IN
	(
		SELECT D.MADT
		FROM DETAI AS D
		WHERE D.KINHPHI > 100
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(D.MADT)
		FROM DETAI AS D
		WHERE D.KINHPHI > 100
	)

--- Q70: Cho biet ten de tai nao ma duoc tat ca cac giao vien cua khoa Sinh hoc tham gia
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		(
			SELECT DISTINCT G.MAGV
			FROM GIAOVIEN AS G, BOMON AS B, KHOA AS K
			WHERE G.MABM = B.MABM AND B.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
		)
		EXCEPT
		(
			SELECT DISTINCT T.MAGV
			FROM THAMGIADT AS T
			WHERE T.MADT = D.MADT
		)
	)
--- NOT EXISTS
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D
WHERE NOT EXISTS 
	(
		SELECT *
		FROM GIAOVIEN AS G, BOMON AS B, KHOA AS K
		WHERE G.MABM = B.MABM AND B.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
		AND NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T
				WHERE T.MADT = D.MADT AND T.MAGV = G.MAGV
			)
	)
--- COUNT
SELECT DISTINCT D.MADT, D.TENDT
FROM DETAI AS D, THAMGIADT AS T, GIAOVIEN AS G, BOMON AS B, KHOA AS K
WHERE D.MADT = T.MADT AND T.MAGV = G.MAGV AND G.MABM = B.MABM AND B.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học'
GROUP BY D.MADT, D.TENDT
HAVING COUNT(DISTINCT T.MAGV) =
	(
		SELECT COUNT(G1.MAGV)
		FROM GIAOVIEN AS G1, BOMON AS B1, KHOA AS K1
		WHERE G1.MABM = B1.MABM AND B1.MAKHOA = K1.MAKHOA AND K1.TENKHOA = N'Sinh học'
	)

--- Q71: Cho biet ma so, ho ten, ngay sinh cua giao vien tham gia tat cac cac cong viec cua de tai 'Ung dung hoa hoc xanh'
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN, G.NGSINH
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT C.SOTT
			FROM CONGVIEC AS C LEFT JOIN DETAI AS D1 ON C.MADT = D1.MADT AND D1.TENDT = N'Ứng dụng hóa học xanh'		
		)
		EXCEPT
		(
			SELECT DISTINCT T1.STT
			FROM THAMGIADT AS T1 LEFT JOIN DETAI AS D2 ON T1.MADT = D2.MADT AND D2.TENDT = N'Ứng dụng hóa học xanh'	
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN, G.NGSINH
FROM GIAOVIEN AS G, THAMGIADT AS T
WHERE G.MAGV = T.MAGV
	AND NOT EXISTS 
	(
		SELECT *
		FROM CONGVIEC AS C LEFT JOIN DETAI AS D1 ON C.MADT = D1.MADT AND D1.TENDT = N'Ứng dụng hóa học xanh'
		WHERE			
			NOT EXISTS
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T1.MAGV = T.MAGV AND T1.MADT = C.MADT AND T1.STT = C.SOTT
			)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN, G.NGSINH
FROM GIAOVIEN AS G, THAMGIADT AS T, DETAI AS D
WHERE G.MAGV = T.MAGV AND T.MADT = D.MADT AND D.TENDT = N'Ứng dụng hóa học xanh'	
	AND T.STT IN
	(
		SELECT DISTINCT C.SOTT
		FROM CONGVIEC AS C, DETAI AS D1
		WHERE C.MADT = D1.MADT AND D1.TENDT = N'Ứng dụng hóa học xanh'		
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.STT) = 
	(
		SELECT COUNT(C.SOTT)
		FROM CONGVIEC AS C, DETAI AS D1
		WHERE C.MADT = D1.MADT AND D1.TENDT = N'Ứng dụng hóa học xanh'		
	)

--- Q72: Cho biet ma so, ho ten, ten bo mon va ten nguoi quan ly chuyen mon cua giao vien tham gia tat ca cac de tai thuoc chu de 'Nghien cuu phat trien'
--- EXCEPT
SELECT DISTINCT G.MAGV, G.HOTEN, B.TENBM, QLCM.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, BOMON AS B, GIAOVIEN AS QLCM
WHERE G.MAGV = T.MAGV AND G.MABM = B.MABM AND G.GVQLCM = QLCM.MAGV
	AND NOT EXISTS 
	(
		(
			SELECT DISTINCT D.MADT
			FROM DETAI AS D, CHUDE AS C
			WHERE D.MACD = C.MACD AND C.TENCD = N'Nghiên cứu phát triển'
		)
		EXCEPT
		(
			SELECT DISTINCT T1.MADT
			FROM THAMGIADT AS T1
			WHERE T.MAGV = T1.MAGV
		)
	)
--- NOT EXISTS
SELECT DISTINCT G.MAGV, G.HOTEN, B.TENBM, QLCM.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, BOMON AS B, GIAOVIEN AS QLCM
WHERE G.MAGV = T.MAGV 
	AND NOT EXISTS 
	(
		SELECT *
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Nghiên cứu phát triển'
		AND NOT EXISTS 
			(
				SELECT *
				FROM THAMGIADT AS T1
				WHERE T.MAGV = T1.MAGV AND T1.MADT = D.MADT
			)
	)
--- COUNT
SELECT DISTINCT G.MAGV, G.HOTEN, B.TENBM, QLCM.HOTEN
FROM GIAOVIEN AS G, THAMGIADT AS T, BOMON AS B, GIAOVIEN AS QLCM
WHERE G.MAGV = T.MAGV 
	AND T.MADT IN
	(
		SELECT D.MADT
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Nghiên cứu phát triển'
	)
GROUP BY G.MAGV, G.HOTEN
HAVING COUNT(DISTINCT T.MADT) = 
	(
		SELECT COUNT(D.MADT)
		FROM DETAI AS D, CHUDE AS C
		WHERE D.MACD = C.MACD AND C.TENCD = N'Nghiên cứu phát triển'
	)